#!/usr/bin/env ruby
# frozen_string_literal: true

require "console"

Console.logger.debug!

class Jobs
	LOG_FILE = File.join(Dir.pwd, "jobs.log")

	def self.start = self.new.start

	def start
		Console.debug(self, "Starting jobs...")

		loop do
			Console.info(self, "Jobs running...")

			sleep 1
		end
		rescue Interrupt
			Console.debug(self, "Exiting jobs...")
			exit
	end
end

Jobs.start