name: Development

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - truffleruby
        
        include:
          - os: 'ubuntu'
            ruby: '2.6'
            env: COVERAGE=PartialSummary,Coveralls
    
    runs-on: ${{matrix.os}}-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: |
        command -v bundler || gem install bundler
        bundle install
    - name: Run tests
      run: ${{matrix.env}} bundle exec rspec
